kriogenia/rede

Cargo.lock, Cargo.toml, bin/Cargo.toml, parser/Cargo.toml, parser/README.md, parser/src/lib.rs
Adds a new `rede_parser` create to the workspace, allowing to use it as the library for the Rede Parser.
=> feat: add parser crate

bin/src/commands/reqwest.rs, bin/src/commands/run.rs, bin/tests/inputs/redirect_loop.toml, bin/tests/run.rs
Adds two new options to `rede run` to allow control of redirections:
- `--no-redirects` is a flag to disable automatic redirection.
- `--max-redirects` to set the number of maximum allowed redirects
=> feat: redirect options

bin/src/commands/reqwest.rs, bin/src/errors.rs, bin/tests/inputs/headers.toml, bin/tests/run.rs
Allows `rede run` to send headers in the requests
=> feat: support headers

Cargo.lock, bin/Cargo.toml, bin/src/commands/reqwest.rs, bin/src/errors.rs, bin/tests/inputs/query_params.toml, bin/tests/run.rs
Allows `rede run` to send the query params of the request defined in the TOML.
=> feat: support query params on rede run

Cargo.lock, Cargo.toml, bin/Cargo.toml, bin/src/commands/reqwest.rs, bin/src/commands/run.rs, bin/src/errors.rs, bin/tests/inputs/body_binary.toml, bin/tests/inputs/body_form_data.toml, bin/tests/inputs/body_form_url_encoded.toml, bin/tests/inputs/wrong_binary.toml, bin/tests/run.rs, bin/tests/util/bin_file_for_test
Allows `rede run` to send the body specified in the `[REQUEST]`. Support all five types.
- **feat: support raw body**
- **feat: support binary body**
- **feat: support multipart body**
- **feat: support form urlencoded**
=> feat: send body on rede run

bin/src/commands/reqwest.rs, bin/src/commands/run.rs
Encapsulates the request logic into a client built from the properties that sends the request.
=> tyding: create client entity

bin/src/commands/run.rs, bin/src/util/read.rs
Whe passing an empty stdin to a command reading from stdin it keeps hanging.
This adds a check that will return an empty buffer if the STDIN is empty.
=> fix: hang on empty stdin

Cargo.lock, bin/Cargo.toml, bin/src/commands.rs, bin/src/commands/run.rs, bin/src/main.rs, bin/src/terminal.rs, bin/tests/root.rs, bin/tests/run.rs
Adds new output messages when using `rede run`.
Allow control of terminal output with three new flags:
- `--no-color`
- `--quiet`
- `--verbose`
- **feat: define verbose and quiet flags**
- **feat: create terminal wrapper**
- **feat: add output on run**
- **tyding: extract command trait**
- **tyding: add macros to root tests**
- **test: improve run tests**
- **feat: --no-color**
=> feat: printing modes

Cargo.lock, bin/Cargo.toml, bin/src/commands.rs, bin/src/commands/run.rs, bin/src/errors.rs, bin/src/terminal.rs
Changes to use `console` crate for coloring and defines a custom miette report handler, allowing tu turn off colors on errors too.
=> fix: --no-color working on errors

parser/src/body.rs
Fixes inconsistent body display
_Looks like the difference between `write!` and `writeln!` is too much for my little brain_
=> fix: body display

Cargo.lock, bin/Cargo.toml, bin/src/commands/reqwest.rs, bin/src/commands/run.rs, bin/src/commands/run/print.rs, bin/src/errors.rs, bin/tests/run.rs
Adds all the printing for incoming responses. By default, just the body.
With verbose... a whole plethora of beautiful and colorful messages. Should this really be the default?
_I will end up changing verbosity to levels right? Yay! More work_
- **feat: print request body**
- **feat: print http version**
- **feat: print response status code**
- **feat: print response url and version**
- **feat: print response headers**
- **feat: print body**
=> feat: print response

bin/src/commands/run/print.rs, bin/src/terminal.rs, bin/tests/inputs/not_found.toml, bin/tests/run.rs
If no body is returned in the response, print the status as fallback in standard verbose mode.
_Always giving the user some kind of feedback is now a feat, huh?_
=> feat: print status as fallback when no body

bin/src/commands.rs, bin/src/commands/run.rs
Now commands and arguments can be inferred from their substrings. Yes, `rede r` will now run `rede run`.
And now the root options are global. Yes, `rede r --q` will now run the request in quiet mode.
Oh, some doc improvements.
_this could have been the PR for the first release but I just decided to something extra because I'm stupid_
- **feat: infering**
- **feat: make printing arguments global**
- **doc: improve rede run help**
=> doc: improve help for release

book/src/SUMMARY.md, book/src/reference_guide/request_dsl.md, book/src/reference_guide/request_dsl/placeholders.md, docs/schema/schema_v0.1.toml, parser/src/request.rs, parser/src/schema.rs, parser/src/schema/body.rs, parser/src/schema/table.rs
Replace the old pathparams with variables.
_i don't know why it didn't cross my mind that the pathparams was irrelevant_
- **feat: convert pathparams a variables**
- **refactor: rename primitive array table**
- **doc: variables**
=> feat: add variables

.github/workflows/ci.yml, Cargo.lock, Makefile, book/src/SUMMARY.md, book/src/reference_guide/request_dsl.md, book/src/reference_guide/request_dsl/input_parameters.md, book/src/reference_guide/request_dsl/placeholders.md, parser/Cargo.toml, parser/src/input_param.rs, parser/src/lib.rs, parser/src/request.rs, parser/src/schema.rs, parser/src/schema/table.rs, placeholders/Cargo.toml, placeholders/src/placeholders.rs
Adds the new `input_params`. Allowing to parse the input parameters in the request
and provide it in the `Request` entity.
- **feat: deserialize input params**
- **refactor: extract input param**
- **feat: add input params to request**
- **feat: hide input_params behind feature**
- **doc: input parameters**
- **chore: bump parser version**
=> feat: parse input parameters

.github/workflows/release-drafter.yml
The release drafter was picking the wrong config for placeholders crate.
=> fix: placeholders release drafter config

.github/drafts/base.yml, .github/drafts/schema.yml, .github/workflows/ci.yml, .github/workflows/publish_schema.yml, .github/workflows/release-drafter.yml, Cargo.lock, Cargo.toml, schema/Cargo.toml, schema/README.md, schema/src/body.rs, schema/src/input_param.rs, schema/src/lib.rs
Extracts the schema parts into a separate crate to ease dependencies.
- feat: create schema crate
- feat: set schema actions
- refactor: move body to schema crate
- refactor: move input params to schema crate
- refactor: move request to schema
=> refactor: extract schema crate

bin/src/commands.rs, bin/src/commands/example.rs, bin/src/commands/run.rs, bin/tests/run.rs
Adds the `--dry-run` flag
﻿- feat: define dry-run and pass global args
- feat: run and example dry-run behavior
=> feat: --dry-run

bin/src/commands/run.rs, bin/src/static/example.toml
Adds placeholders (via variables and input params) to the request
created via `rede example`.
=> feat: placeholders in example

Cargo.lock, bin/Cargo.toml, bin/tests/inputs/json_post.toml, bin/tests/inputs/xml_post.toml, parser/Cargo.toml, parser/src/schema/body.rs, placeholders/Cargo.toml, placeholders/src/placeholders.rs, placeholders/src/renderer.rs
- Expanded Body of parser/src/schema/body.rs for body.json and body.xml.
``` rust
pub(crate) enum Body {
...
#[serde(alias = "json")]
Json(String),
#[serde(alias = "xml")]
Xml(String),
...
}
```
``` rust
impl From<Body> for SchemaBody {
fn from(value: Body) -> Self {
match value {
...
Body::Json(content) => SchemaBody::Raw {
content,
mime: mime::APPLICATION_JSON,
},
Body::Xml(content) => SchemaBody::Raw {
content,
mime: mime::TEXT_XML,
},
...
}
}
```
- Also added `bin/tests/inputs/json_post.toml` and `bin/tests/inputs/xml_post.toml` and tested them on a simple server.
- Also added these lines in bin/Cargo.toml, as it pulls the crates from crates.io and could not accommodate the local changes. These lines can be removed.
``` toml
[dependencies]
rede_parser = "0.2.2"
rede_placeholders = …
```
=> feat: add body.json and body.xml support
